### ISSUE TITLE
secrets are not found

### ISSUE THREAD

**Issue by alexanderreinelt** [rusenask/keel#100]
Hi together,
I'm currently facing some problem when trying to use keel.
I have the following setup. 
+ private repository in quay.io
+ robot account set up in quay.io
+ secret.yaml file provided by quay.io deployed to kubernetes cluster

Then I installed an own package via helm and set the imagePullSecret in the template file of the deployment.
When I now push a new image to the quay.io repo keel should pull automatically the new version but currently it fails to authenticate against quay.io with the error message
```
level=info msg="secrets.defaultGetter.lookupSecrets: no secrets for image found" image=quay.io/group/myImage namespace=default pod_selector="app=myImageApp,release=dangling-aardvark" pods_checked=0 provider=helm registry=quay.io
```

Is there another place where I should reference the secret or am I using it completely wrong?

Thank you in advance.

**Comment by rusenask** [comment]
Hey, can you check whether you have `app` and `release` labels in your chart template? https://github.com/webhookrelay/webhook-demo/blob/master/webhookdemo/templates/deployment.yaml#L5-L8

**Comment by htplbc** [comment]
Having same issue using Artifactory as a private repo. Verified that app and release are in the chart template.

**Comment by alexanderreinelt** [comment]
Yes I have the ```app``` and ```release``` labels in my deployment template.
release is set to ```{{ .Release.Name }}``` and for app I use a hard coded value but I think that should not matter, right?

**Comment by alexanderreinelt** [comment]
okay, I experimented a little bit and now facing the problem that the secret is found but ignored because of the following message
```
level=warning msg="secrets.defaultGetter: supplied secret is not kubernetes.io/dockercfg, ignoring  
[...] type=kubernetes.io/dockerconfigjson
```
so it seems that this type of secret is not supported, but thats the secret I got from quay.io for pulling those images and in the deployment it's working.

**Comment by rusenask** [comment]
ahh yes, there are several different types of secrets, current implementation works with default one from k8s docs:
```kubectl create secret docker-registry myregistrykey --docker-server=https://index.docker.io/v1/ --docker-username=yourUsername --docker-password=yourPassword --docker-email=your@email.com```

you can have a look at https://github.com/rusenask/keel/blob/master/secrets/secrets.go#L120-L140, I think it would be great to support more secret options. If you add more info on how your secret is formed - I could implement it after I am finished with approvals branch.

**Comment by alexanderreinelt** [comment]
Hi, alright when I provide a secret like you describe with the credentials of our robot accounts it can authenticate and updates the container. I can give you the layout of the secret.yaml that I received from quay.io if that would help.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
data:
  .dockerconfigjson:"I assume here comes the encoded auth token"==
type: kubernetes.io/dockerconfigjson
```

**Comment by jeffrichiefs** [comment]
+1 for supporting Quay's robot tokens.

**Comment by jeffrichiefs** [comment]
Also, @alexanderreinelt 's example is a bit wrong. The `"I assume here comes the encoded auth token" part is actually base64 that decodes to:

```
{
  "auths": {
    "quay.io": {
      "auth": "<TOKEN HERE>",
      "email": ""
    }
  }
```

**Comment by rusenask** [comment]
should be fixed with https://github.com/rusenask/keel/pull/107
