### ISSUE TITLE
Allow disabling "preparing deployment update" Slack message

### ISSUE THREAD

**Issue by praseodym** [rusenask/keel#101]
Currently, with Slack notifications enabled, Keel will send a "preparing deployment update" and "deployment update" message in a rapid succession. This "preparing deployment update" message is not useful so we'd really like to disable it.

**Comment by rusenask** [comment]
Hey, do you think it should be additional environment variable or something different?

That "preparing deployment update" was initially added to support a use case where a service that is going to be updated gets notified about upcoming restart :)

**Comment by praseodym** [comment]
I'd suggest filtering based on event level, maybe an environment variable like `SLACK_EVENTLEVEL` (int) and then check whether this is ≥ the event level before sending out the Slack message.

Alternatively the minimum event level could be hardcoded, because I don't really see a use case for sending debug messages to Slack.

**Comment by rusenask** [comment]
sounds good, will add this as a next feature.

**Comment by rusenask** [comment]
should be fixed with https://github.com/rusenask/keel/pull/107

**Comment by praseodym** [comment]
Works like a charm, thank you! I also appreciate adding the old image version in the update message.

**Comment by rusenask** [comment]
Thanks for feedback, I really appreciate it! The old image version was added to make approvals more informative: https://twitter.com/KRusenas/status/916673844110417920.
