### ISSUE TITLE
Quay image pull - invalid bearer token

### ISSUE THREAD

**Issue by jeffrichiefs** [rusenask/keel#104]
`2017/10/02 13:24:17 registry failed ping request, error: Get https://quay.io/v2/: http: non-successful response (status=401 body="{\"error\": \"Invalid bearer token format\"}")`

Secret was created using `kubectl create secret docker-registry` and k8s has no problem pulling the image manually using that secret.

**Comment by rusenask** [comment]
Thanks, I understand there were some details of this added to https://github.com/rusenask/keel/issues/100. I will have a look at this as soon as possible. 

If anyone has time - help would be appreciated, code in question is here https://github.com/rusenask/keel/blob/master/secrets/secrets.go#L132-L166. There we would need a switch statement to process different kinds of configurations.

**Comment by jeffrichiefs** [comment]
Yes, sorry to hit you with this twice.

**Comment by rusenask** [comment]
No worries, I have a few things on quay so will get this resolved and tested.

**Comment by rusenask** [comment]
should be fixed with https://github.com/rusenask/keel/pull/107
