### ISSUE TITLE
Watch myimage:latest without any hooks

### ISSUE THREAD

**Issue by zoobab** [rusenask/keel#11]
Hi,

Does Keel supports polling the registry let's say every minute to check if the sha256 of an image has changed?

Many devs wants that feature, I still have a hard time to understand if that's supported or not.

Best,

**Comment by rusenask** [comment]
Hi,

No, currently there is no such trigger but it could be added. Where do you keep your images? 

Is there a reason not to use webhooks?

Cheers,

**Comment by zoobab** [comment]
As far as I have checked, webhooks on the Docker Hub are only configurable by the owner of the project, so you can't setup them if you are another user, that's already problematic.

I found out some days ago that one of the script I wrote on top of docker-ls outputs the sha256 of an image:

https://github.com/zoobab/docker-ls/tree/master/scripts

$ registry-lslayers zoobab/envvars:latest
sha256:271272071a110ec915a0c6861de10fdfbf5a6740463a1008228329310950b96b

So running it in a loop and triggering a redeploy is easy, but that would be better if such feature would be integrated in a proper go plugin like Keel.

I use both private registries (with login/pwd) in http5000 or https, and the docker hub.

**Comment by rusenask** [comment]
Looks good, I guess the image name is still available in the deployment and registry address could be extracted from container spec? 

So the only tricky part would be providing authentication details as it would be nice to keep Keel stateless. 

Maybe we could use k8s secret, something like this:
```
 kubectl create secret generic keel-somehostname:5000 --from-literal=user=[username] --from-literal=password=[password]
```
So the workflow would be:
1. Add additional label i.e. `trigger=poll` 
2. Create secret for that registry

**Comment by zoobab** [comment]
If you want to try registry-lslayers for debugging, it has support for login/password via setting environment variables:

$ export DOCKER_REGISTRY_LOGIN="mylogin"
$ export DOCKER_REGISTRY_PWD="mypwd"

For the label, you might want to poll the registry every minute, I think that's good enough.

Otherwise +1 for creating a secret in k8s.

**Comment by rusenask** [comment]
I am thinking about multiple registries involved, for example you have 5 different registries or 1 registry with 5 users. 

Also, you probably don't want to redeploy Keel once you add a deployment with new image :) 

Ideally registry secret ref could be on the deployment label as well.

Regarding polling, how about using [cron ](https://github.com/rusenask/cron) style so you can specify a schedule?
```
keel.sh/trigger=poll,@every 1m
keel.sh/registry_username=username_secret_ref
keel.sh/registry_password=password_secret_ref
```

(bought .sh domain so keel.observer label will probably be changed to keel.sh)

**Comment by rusenask** [comment]
@zoobab need your opinion regarding deployment updates.
The thing is that even if Keel detects a change in image digest - there is little it can do to start rolling update. More info here https://github.com/kubernetes/kubernetes/issues/33664.
What Keel could do:
- Option 1: delete/create deployment with the same tag. If `imagePullPolicy: Always` is set - it would pull the new image. Of course - downside is that you would get downtime :) 
- Option 2: upon detecting deployments with `keel.sh/trigger=poll` label - get current digest and update deployment to use the full image name, ie: `andy/busybox@sha256:2aac5e7514fbc77125bd315abe9e7b0257db05fe498af01a58e239ebaccf82a8` so when the new digest is available, all the niceness of k8s rolling updates is available. 
- Option 3: use one of the hacks provided in the same thread, ie: add, remove label. 

I would prefer option 2. Need opinions.

**Comment by zoobab** [comment]
Hi,

I am against version 2 for the reason you need an external service to make it work. It should work without it. For example, I do have a k8s cluster which is disconnected from the internet for security reasons, but is connected to a registry where images are pushed in a dedicated LAN. I don't think it would be a problem scrap the current deployment and have some downtime, because the main purpose is to get it running asap and get some feedback for the developer.

**Comment by rusenask** [comment]
option 2 wouldn't mean that an external service (dockerhub) is required. It can work with internal registries as well, image would be something like `localhost.localdomain/foo/bar@sha256:2aac5e7514fbc77125bd315abe9e7b0257db05fe498af01a58e239ebaccf82a8`

**Comment by rusenask** [comment]
partially implemented in https://github.com/rusenask/keel/pull/26, 
check https://github.com/rusenask/keel#polling for details.
I plan to add authenticated option as the next step.

**Comment by rusenask** [comment]
fully implemented by now.
