### ISSUE TITLE
CrashLoopBackOff

### ISSUE THREAD

**Issue by sabrehagen** [rusenask/keel#17]
I'm not sure if this is a symptom of the other two bugs I've logged, or an independent issue. Feel free to close if it is a duplicate.

![keel-crash](https://user-images.githubusercontent.com/1094600/27766878-65f2f180-5f24-11e7-9289-82ff878562e8.png)

**Comment by rusenask** [comment]
yep, this is due to https://github.com/rusenask/keel/issues/16
