### ISSUE TITLE
AWS ECR support

### ISSUE THREAD

**Issue by rimusz** [rusenask/keel#51]

**Comment by rusenask** [comment]
This can be quite nasty as ECR doesn't have any webhooks/SNS to inform about new messages. Apparently the only way to know about new image is to parse logs. Maybe polling trigger for this could be best approach.

**Comment by rimusz** [comment]
polling trigger with private registries support then 👍

**Comment by rusenask** [comment]
Polling trigger should work, if not - please reopen.
