### ISSUE TITLE
Helm Provider: rpc error (timeout) during update of release

### ISSUE THREAD

**Issue by fujin** [rusenask/keel#54]
I got a timeout during the update of a helm release:

```
time="2017-07-25T23:39:04Z" level=error msg="provider.helm: failed to apply plan" error="rpc error: code = Unknown desc = timed out waiting for the condition" name=is-app namespace=default
```

```
time="2017-07-25T23:38:33Z" level=debug msg="trigger.pubsub: got message" action=INSERT image_name="dd-engineering/identity:1.8.1" tag=1.8.1 
time="2017-07-25T23:38:33Z" level=info msg="provider.helm: processing event" registry= repository=gcr.io/dd-engineering/identity tag=1.8.1 
time="2017-07-25T23:38:33Z" level=info msg="provider.kubernetes: processing event" registry= repository=gcr.io/dd-engineering/identity tag=1.8.1 
time="2017-07-25T23:38:33Z" level=info msg="provider.kubernetes: no impacted deployments found for this event" image=gcr.io/dd-engineering/identity tag=1.8.1 
image.tag
gcr.io/dd-engineering/identity
time="2017-07-25T23:38:33Z" level=info msg="provider.helm: current image version" container_image=gcr.io/dd-engineering/identity current_version=1.6.1 name=is-app namespace=default policy=minor 
time="2017-07-25T23:38:33Z" level=info msg="provider.helm: checked version, deciding whether to update" container_image=gcr.io/dd-engineering/identity current_version=1.6.1 name=is-app namespace=default new_version=1.8.1 policy=minor should_update=true 
time="2017-07-25T23:38:33Z" level=info msg="provider.helm: impacted release tags found" container_image=gcr.io/dd-engineering/identity policy=minor target_image=gcr.io/dd-engineering/identity target_image_tag=1.8.1
```

It seems like the code around here https://github.com/rusenask/keel/blob/28553b3e9db8076de8c5b0d50eb664c4b6f7e92f/provider/helm/helm.go#L269-L285 (haven't dug much deeper than that I'm afraid)

**Comment by rusenask** [comment]
Hi! there is 30 seconds timeout for release upgrades, I guess it's a bit optimistic if you have larger images?

**Comment by fujin** [comment]
@rusenask yea, that could well be it. this image is 625MB (has a lot of runtime tooling) and there are a number of replicas in the deployment (a HPA controls it, so it varies, but anywhere from 2~36)

`gcr.io/dd-engineering/identity                 1.8.1                     69916c4eff80        7 hours ago         625MB`

the ability to control the timeout via configuration would be welcome as a workaround for now!

**Comment by fujin** [comment]
Is that timeout @ https://github.com/rusenask/keel/blob/28553b3e9db8076de8c5b0d50eb664c4b6f7e92f/provider/helm/helm.go#L329 ?

**Comment by rusenask** [comment]
Yeah that's the one. Are you modifying timeout when updating releases with CLI? I see default 300 seconds in helm. I can quickly bump it and add configuration later.

**Comment by fujin** [comment]
@rusenask we have not had to modify the timeout when updating releases with CLI, no. 

that sounds awesome to me. :1st_place_medal: the Helm stuff looks great so far.

**Comment by rusenask** [comment]
created new release with `0.4.1`, cloud.docker.com is building it now (although it's quite slow) so image should be available soon. Configurable timeout could be in values.yml with other config:
```
keel:
  # keel policy (all/major/minor/patch/force)
  policy: all
  # update timeout in seconds (defaults to 300)
  timeout: 9001
  # images to track and update
  images:
    - repository: image.repository # [1]
      tag: image.tag  # [2]
```
Would that make sense?

**Comment by theckman** [comment]
@rusenask (I work with @fujin) -- that would definitely work for us!

**Comment by fujin** [comment]
@rusenask yup, looks good to me. :+1:

**Comment by rusenask** [comment]
okay, `0.4.1` is available, just noticed that my own Keel upgraded itself and sent notification to slack faster than I got an email from dockerhub. Hope that helps!

**Comment by fujin** [comment]
confirming fixed in 0.4.1:
![image](https://user-images.githubusercontent.com/6873/28610410-5ac5a8f4-723c-11e7-8018-7f20aac42645.png)

**Comment by rusenask** [comment]
I guess it would be nice to see how long release update took, from time it looks like ~1 minute :)

P.S. Bonus feature -  if you invite Keel to your channel (or you can message it directly) you can:
![screen shot 2017-07-26 at 09 07 41](https://user-images.githubusercontent.com/9080105/28610902-eafee774-71e1-11e7-9ea3-93ec4f909cb5.png)

**Comment by theckman** [comment]
@rusenask for the latest test deployment, webhooks were 47 seconds apart.

**Comment by theckman** [comment]
I guess I should mention that this is our smallest environment with only two Pods in the deployment. Other environments may have 6+.

**Comment by rusenask** [comment]
That timeout is for single helm deployment, each deployment will have a refreshed timeout. Since Helm provider is slightly different from k8s - it would make sense to start helm upgrades in parallel (as it's waiting for ok/not ok) .
