### ISSUE TITLE
Ignoring the repository version and assuming SemVer means 10.4 -> 10.4.0

### ISSUE THREAD

**Issue by stickycode** [rusenask/keel#80]
I use SemVer 'almost', but unless there is actual need for a patch version I omit it. 

IME its just confusing and does not add any value, you either broke the contract or you didn't. I find that developers use minor and patch interchangeably on a whim and as a result they might as well be one number.

Well and I don't use 0 because 0 means nothing and if there is nothing why deploy. 

Anyways can we just parse the version match which works fine but use the original value not the semverfied one? Without starting a religious war maybe?

**Comment by stickycode** [comment]
see #81 

worth noting I created the PR without compiling anything, its seems simple enough though that I might just get away with it

**Comment by rusenask** [comment]
Thanks, should work. We already had similar a issue with other versions where I thought I fixed it but apparently forgot about that `NewAvailable` function :) If you could open it against `develop` branch that would be great.

**Comment by stickycode** [comment]
See #82 which is to develop not master

**Comment by rusenask** [comment]
Tagged new patch release with the change https://github.com/rusenask/keel/releases/tag/0.4.5. Docker cloud builder should produce an image soon :) Thanks!

**Comment by stickycode** [comment]
Working for me now
