### ISSUE TITLE
Rollback example?

### ISSUE THREAD

**Issue by StevenACoffman** [rusenask/keel#97]
I was wondering if there were examples of common workflows, especially with regards to rollbacks. I was contemplating doing this given keel with a *kubernetes* provider, a policy of *force* (one policy on docker tag `staging` and one on tag `prod`), and *polling* a private docker repository:

```
docker push myregistry.com/myimage:v1.2.3
docker tag myregistry.com/myimage:v1.2.3 myregistry.com/myimage:staging
docker push myregistry.com/myimage:staging
```
Keel then deploys the app to my kubernetes staging cluster, and then keel will send a notification via webhook to my staging jenkins to run integration tests. If these, succeed, then I do this:

```
docker tag myregistry.com/myimage:v1.2.3 myregistry.com/myimage:prod
docker push myregistry.com/myimage:prod
```
Keel then deploys the app to my kubernetes prod cluster.

If we notice problems in production (increased error rates, etc.) with `1.2.3` and want to roll back to `1.2.2`, I think I then can *manually* do this:

```
docker tag myregistry.com/myimage:v1.2.2 myregistry.com/myimage:prod
docker push myregistry.com/myimage:prod
```
Keel would notice the tag changes, and deploy things back to how they had been before. Is that an accurate understanding? Are there better/recommended ways to do this?

**Comment by rusenask** [comment]
Hi,
Since `v1.2.2` < `v1.2.3` it wouldn't update to the previous version. My current suggestion would 
 be to use the tool that detects errors to revert back to previous version. 

As for Jenkins notification to start integration tests - would current webhook notifications be enough (https://keel.sh/user-guide/notifications/#webhooks) or something different is required?

**Comment by rusenask** [comment]
yes, when the policy is `force` - it will always go through

**Comment by StevenACoffman** [comment]
Awesome! I can iterate on a better solution, but I appreciate you helping me think an initial one.

**Comment by rusenask** [comment]
Cheers, I have plans to add auto rollback into Keel itself, since it's already keeping replica set revision history so it wouldn't be too hard to rollback to previous one if healthchecks are failing. But I somehow find this to need a human touch.. :)
